let negotiations = [
  {
    id: 1,
    client: {
      fullName: "Putnam Huckel",
      status: "active",
      gender: "Male",
      addr: "Room 1982",
      email: "phuckel2o@marriott.com",
      active_conversation: 97,
    },
    "real-state": {
      empreendimento: "empreendimento 2",
      bairro: "Centro",
      type: "residencial",
      price: 825000.5,
      status: "indisponível",
    },
    createdAt: "8/17/2023",
    updates: [   {
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque repudiandae beatae laborum, nam excepturi iure deserunt fugit, similique nulla eaque aperiam consequatur et libero praesentium. Repellendus architecto consectetur reiciendis distinctio.',
      proposal: "",
      createdAt: new Date(),
    },
    {
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque repudiandae beatae laborum, nam excepturi iure deserunt fugit, similique nulla eaque aperiam consequatur et libero praesentium. Repellendus architecto consectetur reiciendis distinctio.',
      proposal: "",
      createdAt: new Date(),
    },
    {
      description: 'Lorem ipsum dolor sit amet consectetur .',
      proposal: "",
      createdAt: new Date(),
    },
    {
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque repudiandae beatae laborumo.',
      proposal: "",

      createdAt: new Date(),
    },
    {
      description: 'Lorem ipsum dolor sit amet cendis distinctio.',
      proposal: "R$ 980.000,00",
      createdAt: new Date(),
    },],
    proposals: [{}],
    status: true,
  },
  {
    id: 2,
    client: {
      fullName: "Krisha Huckel",
      status: "active",
      gender: "Male",
      addr: "Room 1982",
      email: "krisha292@marriott.com",
      active_conversation: 97,
    },
    "real-state": {
      empreendimento: "empreendimento 2",
      bairro: "Centro",
      type: "casa",
      price: 1225000.5,
      status: "active",
    },
    createdAt: "6/6/2023",
    updates: [{}],
    proposals: [{}],
    status: true,
  },
  // {
  //   id: 3,
  //   client: "Agnese Falkinder",
  //   "real-state": "Ntag",
  //   createdAt: "11/13/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 4,
  //   client: "Mart Harsum",
  //   "real-state": "Zoomzone",
  //   createdAt: "7/8/2023",
  //   updates: [{}, {}],
  //   proposals: [{}, {}],
  //   status: false,
  // },
  // {
  //   id: 5,
  //   client: "Bobine Swiggs",
  //   "real-state": "Plajo",
  //   createdAt: "12/13/2023",
  //   updates: [{}],
  //   proposals: [{}, {}],
  //   status: true,
  // },
  // {
  //   id: 6,
  //   client: "Joella Jovasevic",
  //   "real-state": "Brightbean",
  //   createdAt: "9/7/2023",
  //   updates: [{}],
  //   proposals: [],
  //   status: true,
  // },
  // {
  //   id: 7,
  //   client: "Gustav Niccolls",
  //   "real-state": "Cogibox",
  //   createdAt: "3/10/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 8,
  //   client: "Verina Pavie",
  //   "real-state": "Dabtype",
  //   createdAt: "1/11/2024",
  //   updates: [],
  //   proposals: [],
  //   status: true,
  // },
  // {
  //   id: 9,
  //   client: "Halimeda Casassa",
  //   "real-state": "Demizz",
  //   createdAt: "10/22/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 10,
  //   client: "Efrem MacRury",
  //   "real-state": "Rhybox",
  //   createdAt: "10/7/2023",
  //   updates: [{}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 11,
  //   client: "Hildagarde Renison",
  //   "real-state": "Mynte",
  //   createdAt: "9/13/2023",
  //   updates: [{}],
  //   proposals: [{}],
  //   status: true,
  // },
  // {
  //   id: 12,
  //   client: "Mayor L'Episcopio",
  //   "real-state": "Realblab",
  //   createdAt: "3/9/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 13,
  //   client: "Biron Collister",
  //   "real-state": "Roomm",
  //   createdAt: "6/14/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 14,
  //   client: "Mia Coules",
  //   "real-state": "Pixoboo",
  //   createdAt: "9/29/2023",
  //   updates: [{}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 15,
  //   client: "Cris Maypole",
  //   "real-state": "Tagcat",
  //   createdAt: "1/12/2024",
  //   updates: [],
  //   proposals: [{}],
  //   status: true,
  // },
  // {
  //   id: 16,
  //   client: "Alexis Whetton",
  //   "real-state": "Trilith",
  //   createdAt: "6/18/2023",
  //   updates: [{}],
  //   proposals: [{}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 17,
  //   client: "Kai Straun",
  //   "real-state": "Brightdog",
  //   createdAt: "6/23/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 18,
  //   client: "Leisha Measor",
  //   "real-state": "Youspan",
  //   createdAt: "10/11/2023",
  //   updates: [],
  //   proposals: [{}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 19,
  //   client: "Nichol Winslet",
  //   "real-state": "Feedbug",
  //   createdAt: "9/19/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 20,
  //   client: "Francene Smurfitt",
  //   "real-state": "Vitz",
  //   createdAt: "11/26/2023",
  //   updates: [],
  //   proposals: [{}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 21,
  //   client: "Gamaliel Morstatt",
  //   "real-state": "JumpXS",
  //   createdAt: "7/21/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [],
  //   status: true,
  // },
  // {
  //   id: 22,
  //   client: "Laural Bachelor",
  //   "real-state": "Zoomzone",
  //   createdAt: "10/31/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 23,
  //   client: "Tatum Hartzenberg",
  //   "real-state": "Wikizz",
  //   createdAt: "6/4/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 24,
  //   client: "Ewan Johanssen",
  //   "real-state": "Roodel",
  //   createdAt: "1/16/2024",
  //   updates: [{}, {}],
  //   proposals: [{}, {}],
  //   status: true,
  // },
  // {
  //   id: 25,
  //   client: "Lorne Hiseman",
  //   "real-state": "Thoughtsphere",
  //   createdAt: "7/24/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}, {}],
  //   status: true,
  // },
  // {
  //   id: 26,
  //   client: "Seumas Trotman",
  //   "real-state": "Skyble",
  //   createdAt: "10/5/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [{}],
  //   status: true,
  // },
  // {
  //   id: 27,
  //   client: "Liesa Larmet",
  //   "real-state": "Twitterlist",
  //   createdAt: "1/4/2024",
  //   updates: [],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 28,
  //   client: "Karalynn Albers",
  //   "real-state": "Eadel",
  //   createdAt: "12/20/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 29,
  //   client: "Elsa Roberti",
  //   "real-state": "Voonder",
  //   createdAt: "8/15/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 30,
  //   client: "Klaus Stanistreet",
  //   "real-state": "Mynte",
  //   createdAt: "7/3/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 31,
  //   client: "Antone Seignior",
  //   "real-state": "Thoughtsphere",
  //   createdAt: "5/25/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 32,
  //   client: "Ed Robotham",
  //   "real-state": "Rhynyx",
  //   createdAt: "12/14/2023",
  //   updates: [],
  //   proposals: [],
  //   status: true,
  // },
  // {
  //   id: 33,
  //   client: "Ashil Redhole",
  //   "real-state": "Riffpedia",
  //   createdAt: "12/16/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [{}],
  //   status: false,
  // },
  // {
  //   id: 34,
  //   client: "Harp Taw",
  //   "real-state": "Twitterlist",
  //   createdAt: "8/5/2023",
  //   updates: [],
  //   proposals: [{}],
  //   status: true,
  // },
  // {
  //   id: 35,
  //   client: "Lester Haycraft",
  //   "real-state": "Gabvine",
  //   createdAt: "4/28/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 36,
  //   client: "Bella Shenton",
  //   "real-state": "Yacero",
  //   createdAt: "3/18/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}],
  //   status: false,
  // },
  // {
  //   id: 37,
  //   client: "Chuck Minghella",
  //   "real-state": "Fadeo",
  //   createdAt: "9/2/2023",
  //   updates: [{}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 38,
  //   client: "Melania Gillmor",
  //   "real-state": "Fatz",
  //   createdAt: "9/19/2023",
  //   updates: [{}, {}],
  //   proposals: [{}],
  //   status: false,
  // },
  // {
  //   id: 39,
  //   client: "Silvester Earp",
  //   "real-state": "Photolist",
  //   createdAt: "10/9/2023",
  //   updates: [],
  //   proposals: [{}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 40,
  //   client: "Steven Culpin",
  //   "real-state": "Vipe",
  //   createdAt: "4/23/2023",
  //   updates: [{}, {}],
  //   proposals: [{}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 41,
  //   client: "Clarie Kingzeth",
  //   "real-state": "Babbleblab",
  //   createdAt: "12/17/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 42,
  //   client: "Ermanno Oleshunin",
  //   "real-state": "Oyoba",
  //   createdAt: "2/6/2024",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 43,
  //   client: "Alice Pergens",
  //   "real-state": "Youspan",
  //   createdAt: "7/31/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 44,
  //   client: "Reuven Ferreira",
  //   "real-state": "Ailane",
  //   createdAt: "7/25/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 45,
  //   client: "Tally Blaydes",
  //   "real-state": "Oodoo",
  //   createdAt: "11/22/2023",
  //   updates: [{}, {}],
  //   proposals: [{}],
  //   status: false,
  // },
  // {
  //   id: 46,
  //   client: "Felicle Shotter",
  //   "real-state": "Wordpedia",
  //   createdAt: "4/9/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 47,
  //   client: "Domini Zarb",
  //   "real-state": "Skiptube",
  //   createdAt: "2/6/2024",
  //   updates: [{}, {}, {}],
  //   proposals: [{}, {}],
  //   status: false,
  // },
  // {
  //   id: 48,
  //   client: "Dolores Purry",
  //   "real-state": "Minyx",
  //   createdAt: "3/23/2023",
  //   updates: [{}, {}],
  //   proposals: [],
  //   status: true,
  // },
  // {
  //   id: 49,
  //   client: "Noby Ivantsov",
  //   "real-state": "Skaboo",
  //   createdAt: "5/17/2023",
  //   updates: [{}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 50,
  //   client: "Carver Ratcliff",
  //   "real-state": "Tekfly",
  //   createdAt: "4/22/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 51,
  //   client: "Janenna Corneille",
  //   "real-state": "Bluejam",
  //   createdAt: "6/6/2023",
  //   updates: [{}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 52,
  //   client: "Nigel Vallentine",
  //   "real-state": "Lazz",
  //   createdAt: "4/15/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 53,
  //   client: "Fayth McGaw",
  //   "real-state": "Camido",
  //   createdAt: "10/11/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}],
  //   status: true,
  // },
  // {
  //   id: 54,
  //   client: "Lalo Tansly",
  //   "real-state": "Flashspan",
  //   createdAt: "11/17/2023",
  //   updates: [],
  //   proposals: [{}],
  //   status: true,
  // },
  // {
  //   id: 55,
  //   client: "Bernice Trittam",
  //   "real-state": "Twitterlist",
  //   createdAt: "12/20/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 56,
  //   client: "Dunn Gobourn",
  //   "real-state": "Dynava",
  //   createdAt: "5/18/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [{}],
  //   status: true,
  // },
  // {
  //   id: 57,
  //   client: "Sarine Klaes",
  //   "real-state": "Teklist",
  //   createdAt: "11/6/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 58,
  //   client: "Shanon Sneezum",
  //   "real-state": "Muxo",
  //   createdAt: "12/7/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 59,
  //   client: "Kent Dootson",
  //   "real-state": "Tekfly",
  //   createdAt: "10/20/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [],
  //   status: true,
  // },
  // {
  //   id: 60,
  //   client: "Cathryn Neathway",
  //   "real-state": "Tagpad",
  //   createdAt: "4/16/2023",
  //   updates: [{}],
  //   proposals: [{}],
  //   status: true,
  // },
  // {
  //   id: 61,
  //   client: "Avigdor Hefner",
  //   "real-state": "Meevee",
  //   createdAt: "11/18/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 62,
  //   client: "Timofei Overshott",
  //   "real-state": "Skinix",
  //   createdAt: "5/28/2023",
  //   updates: [],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 63,
  //   client: "Uriah Pochon",
  //   "real-state": "Jabbertype",
  //   createdAt: "6/1/2023",
  //   updates: [{}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 64,
  //   client: "Jeri Iwanczyk",
  //   "real-state": "Tagchat",
  //   createdAt: "3/3/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 65,
  //   client: "Minni Jolland",
  //   "real-state": "Feednation",
  //   createdAt: "7/7/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 66,
  //   client: "Lorenzo Colquit",
  //   "real-state": "Wordware",
  //   createdAt: "11/25/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 67,
  //   client: "Darrell Lattey",
  //   "real-state": "Tagpad",
  //   createdAt: "4/9/2023",
  //   updates: [{}],
  //   proposals: [{}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 68,
  //   client: "Maribeth Adamiec",
  //   "real-state": "Plambee",
  //   createdAt: "8/5/2023",
  //   updates: [{}, {}],
  //   proposals: [{}, {}],
  //   status: true,
  // },
  // {
  //   id: 69,
  //   client: "Junia McKenny",
  //   "real-state": "Youtags",
  //   createdAt: "10/29/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 70,
  //   client: "Merle Dougan",
  //   "real-state": "Thoughtstorm",
  //   createdAt: "9/25/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 71,
  //   client: "Valry Ferrea",
  //   "real-state": "Zoonder",
  //   createdAt: "8/16/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}],
  //   status: false,
  // },
  // {
  //   id: 72,
  //   client: "Trumaine Wyllcocks",
  //   "real-state": "Brightbean",
  //   createdAt: "1/13/2024",
  //   updates: [{}, {}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 73,
  //   client: "Alard Scanes",
  //   "real-state": "Tanoodle",
  //   createdAt: "2/17/2024",
  //   updates: [{}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 74,
  //   client: "Codi Tillot",
  //   "real-state": "Jazzy",
  //   createdAt: "4/2/2023",
  //   updates: [{}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 75,
  //   client: "Shawna Alastair",
  //   "real-state": "Ntags",
  //   createdAt: "4/5/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}, {}],
  //   status: true,
  // },
  // {
  //   id: 76,
  //   client: "Oren Fillary",
  //   "real-state": "Voomm",
  //   createdAt: "12/31/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [{}],
  //   status: false,
  // },
  // {
  //   id: 77,
  //   client: "Ester Agutter",
  //   "real-state": "Zoonoodle",
  //   createdAt: "3/23/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}],
  //   status: false,
  // },
  // {
  //   id: 78,
  //   client: "Evita Short",
  //   "real-state": "Fivechat",
  //   createdAt: "4/7/2023",
  //   updates: [],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 79,
  //   client: "Mord McCloid",
  //   "real-state": "Roomm",
  //   createdAt: "5/28/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}],
  //   status: true,
  // },
  // {
  //   id: 80,
  //   client: "Greta Palmer",
  //   "real-state": "Mycat",
  //   createdAt: "8/14/2023",
  //   updates: [{}],
  //   proposals: [{}],
  //   status: true,
  // },
  // {
  //   id: 81,
  //   client: "Godfrey Krier",
  //   "real-state": "Twitterbridge",
  //   createdAt: "6/24/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}, {}],
  //   status: false,
  // },
  // {
  //   id: 82,
  //   client: "Marylou Breadon",
  //   "real-state": "Browsecat",
  //   createdAt: "6/24/2023",
  //   updates: [{}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 83,
  //   client: "Brina MacDonagh",
  //   "real-state": "Flashset",
  //   createdAt: "9/29/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [{}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 84,
  //   client: "Cam Duckett",
  //   "real-state": "Linktype",
  //   createdAt: "11/8/2023",
  //   updates: [],
  //   proposals: [{}, {}],
  //   status: true,
  // },
  // {
  //   id: 85,
  //   client: "Deeann Orrocks",
  //   "real-state": "Kimia",
  //   createdAt: "5/27/2023",
  //   updates: [{}],
  //   proposals: [{}],
  //   status: false,
  // },
  // {
  //   id: 86,
  //   client: "Tillie Banthorpe",
  //   "real-state": "Photolist",
  //   createdAt: "11/18/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 87,
  //   client: "Nicko Sandhill",
  //   "real-state": "Browsezoom",
  //   createdAt: "9/13/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 88,
  //   client: "Russell Philippsohn",
  //   "real-state": "Tazzy",
  //   createdAt: "11/4/2023",
  //   updates: [{}],
  //   proposals: [],
  //   status: true,
  // },
  // {
  //   id: 89,
  //   client: "Ransell Maddox",
  //   "real-state": "Livefish",
  //   createdAt: "5/16/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}],
  //   status: false,
  // },
  // {
  //   id: 90,
  //   client: "Minta Petracchi",
  //   "real-state": "Centidel",
  //   createdAt: "8/10/2023",
  //   updates: [{}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: true,
  // },
  // {
  //   id: 91,
  //   client: "Myron Janca",
  //   "real-state": "Browsedrive",
  //   createdAt: "11/4/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 92,
  //   client: "Annice Chaize",
  //   "real-state": "Buzzster",
  //   createdAt: "7/13/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 93,
  //   client: "Cornie Wittering",
  //   "real-state": "Janyx",
  //   createdAt: "9/25/2023",
  //   updates: [],
  //   proposals: [{}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 94,
  //   client: "Kerri Casse",
  //   "real-state": "Centidel",
  //   createdAt: "1/5/2024",
  //   updates: [{}],
  //   proposals: [],
  //   status: true,
  // },
  // {
  //   id: 95,
  //   client: "Sigfrid Blofield",
  //   "real-state": "Twitterwire",
  //   createdAt: "8/10/2023",
  //   updates: [{}],
  //   proposals: [{}, {}],
  //   status: false,
  // },
  // {
  //   id: 96,
  //   client: "Caroline Creer",
  //   "real-state": "Jabberbean",
  //   createdAt: "11/27/2023",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}],
  //   status: true,
  // },
  // {
  //   id: 97,
  //   client: "Janeen Giacubbo",
  //   "real-state": "Brightbean",
  //   createdAt: "2/12/2024",
  //   updates: [{}, {}, {}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: false,
  // },
  // {
  //   id: 98,
  //   client: "Bridgette Aitchinson",
  //   "real-state": "Dynabox",
  //   createdAt: "9/1/2023",
  //   updates: [{}, {}],
  //   proposals: [],
  //   status: false,
  // },
  // {
  //   id: 99,
  //   client: "Quinn Wallenger",
  //   "real-state": "Thoughtbridge",
  //   createdAt: "6/22/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}],
  //   status: false,
  // },
  // {
  //   id: 100,
  //   client: "Hodge Scoffins",
  //   "real-state": "Fadeo",
  //   createdAt: "8/23/2023",
  //   updates: [{}, {}, {}, {}],
  //   proposals: [{}, {}, {}, {}, {}],
  //   status: true,
  // },
];

export async function getNegotiations(name) {
  await new Promise((resolve) => setTimeout(resolve, 1000));

  if (name) {
    negotiations = negotiations.filter((negotiation) =>
      negotiation.client.includes(name)
    );
  }

  return negotiations;
}
export async function getNegotiationById(id) {
  await new Promise((resolve) => setTimeout(resolve, 1000));
  const negotiation = negotiations.find(
    (negotiation) => negotiation.id.toString() === id.toString()
  );
  return negotiation ? negotiation : null;
}
