export async function getClients(name, status) {
  await new Promise((resolve) => setTimeout(resolve, 1000));
  let clients = [
    {
      fullName: "Laurens Columbell",
      status: "active",
      gender: "Male",
      addr: "PO Box 92864",
      email: "lcolumbell0@weebly.com",
      active_conversation: 1,
    },
    {
      fullName: "Odelle Gareisr",
      status: "active",
      gender: "Female",
      addr: "Room 350",
      email: "ogareisr1@networkadvertising.org",
      active_conversation: 2,
    },
    {
      fullName: "Sidnee Barrand",
      status: "active",
      gender: "Male",
      addr: "Suite 30",
      email: "sbarrand2@joomla.org",
      active_conversation: 3,
    },
    {
      fullName: "Karyn Ondra",
      status: "inactive",
      gender: "Female",
      addr: "Suite 44",
      email: "kondra3@eepurl.com",
      active_conversation: 4,
    },
    {
      fullName: "Veronika McGrae",
      status: "inactive",
      gender: "Female",
      addr: "PO Box 70611",
      email: "vmcgrae4@skype.com",
      active_conversation: 5,
    },
    {
      fullName: "Mallory Runham",
      status: "active",
      gender: "Female",
      addr: "PO Box 41420",
      email: "mrunham5@t-online.de",
      active_conversation: 6,
    },

    /*


    {
      fullName: "Che McGuff",
      status: "active",
      gender: "Male",
      addr: "Apt 1384",
      email: "cmcguff6@deliciousdays.com",
      active_conversation: 7,
    },
    {
      fullName: "Boote Couche",
      status: "inactive",
      gender: "Male",
      addr: "8th Floor",
      email: "bcouche7@sakura.ne.jp",
      active_conversation: 8,
    },
    {
      fullName: "Llewellyn Drakeford",
      status: "active",
      gender: "Agender",
      addr: "PO Box 10495",
      email: "ldrakeford8@csmonitor.com",
      active_conversation: 9,
    },
    {
      fullName: "Caryn Kornas",
      status: "active",
      gender: "Female",
      addr: "PO Box 47040",
      email: "ckornas9@cbslocal.com",
      active_conversation: 10,
    },
    {
      fullName: "Ade McAw",
      status: "active",
      gender: "Male",
      addr: "PO Box 8095",
      email: "amcawa@howstuffworks.com",
      active_conversation: 11,
    },
    {
      fullName: "Wallis Childes",
      status: "active",
      gender: "Male",
      addr: "Apt 30",
      email: "wchildesb@census.gov",
      active_conversation: 12,
    },
    {
      fullName: "Dermot Rodriguez",
      status: "active",
      gender: "Male",
      addr: "15th Floor",
      email: "drodriguezc@ezinearticles.com",
      active_conversation: 13,
    },
    {
      fullName: "Reider Grinnov",
      status: "inactive",
      gender: "Male",
      addr: "6th Floor",
      email: "rgrinnovd@state.gov",
      active_conversation: 14,
    },
    {
      fullName: "Olav Martschik",
      status: "active",
      gender: "Male",
      addr: "Apt 846",
      email: "omartschike@prweb.com",
      active_conversation: 15,
    },
    {
      fullName: "Rochella Peggs",
      status: "active",
      gender: "Female",
      addr: "Suite 97",
      email: "rpeggsf@homestead.com",
      active_conversation: 16,
    },
    {
      fullName: "Barnabe Reeves",
      status: "active",
      gender: "Male",
      addr: "Suite 1",
      email: "breevesg@forbes.com",
      active_conversation: 17,
    },
    {
      fullName: "Gilbertine Sebastian",
      status: "active",
      gender: "Female",
      addr: "6th Floor",
      email: "gsebastianh@mediafire.com",
      active_conversation: 18,
    },
    {
      fullName: "Giraldo Fanshawe",
      status: "active",
      gender: "Male",
      addr: "20th Floor",
      email: "gfanshawei@nature.com",
      active_conversation: 19,
    },
    {
      fullName: "Odette Widdecombe",
      status: "active",
      gender: "Agender",
      addr: "Apt 9",
      email: "owiddecombej@sogou.com",
      active_conversation: 20,
    },
    {
      fullName: "Kirby Spanswick",
      status: "inactive",
      gender: "Male",
      addr: "Suite 98",
      email: "kspanswickk@arizona.edu",
      active_conversation: 21,
    },
    {
      fullName: "Adelaida Musk",
      status: "active",
      gender: "Female",
      addr: "13th Floor",
      email: "amuskl@gizmodo.com",
      active_conversation: 22,
    },
    {
      fullName: "Grove Bungey",
      status: "inactive",
      gender: "Male",
      addr: "Room 1537",
      email: "gbungeym@newsvine.com",
      active_conversation: 23,
    },
    {
      fullName: "Stefania Boissier",
      status: "active",
      gender: "Female",
      addr: "Apt 1311",
      email: "sboissiern@t.co",
      active_conversation: 24,
    },
    {
      fullName: "Robenia Lankester",
      status: "inactive",
      gender: "Female",
      addr: "PO Box 19688",
      email: "rlankestero@icq.com",
      active_conversation: 25,
    },
    {
      fullName: "Abbe Peaple",
      status: "inactive",
      gender: "Male",
      addr: "Suite 24",
      email: "apeaplep@cloudflare.com",
      active_conversation: 26,
    },
    {
      fullName: "Georgie Newark",
      status: "inactive",
      gender: "Female",
      addr: "Suite 51",
      email: "gnewarkq@elegantthemes.com",
      active_conversation: 27,
    },
    {
      fullName: "Vania Duligall",
      status: "active",
      gender: "Female",
      addr: "Apt 37",
      email: "vduligallr@printfriendly.com",
      active_conversation: 28,
    },
    {
      fullName: "Dehlia Braundt",
      status: "inactive",
      gender: "Genderqueer",
      addr: "10th Floor",
      email: "dbraundts@oaic.gov.au",
      active_conversation: 29,
    },
    {
      fullName: "Rubia Renn",
      status: "active",
      gender: "Female",
      addr: "Room 800",
      email: "rrennt@amazon.co.jp",
      active_conversation: 30,
    },
    {
      fullName: "Idalia Haydock",
      status: "inactive",
      gender: "Female",
      addr: "Apt 556",
      email: "ihaydocku@wsj.com",
      active_conversation: 31,
    },
    {
      fullName: "Iosep Noor",
      status: "inactive",
      gender: "Male",
      addr: "11th Floor",
      email: "inoorv@narod.ru",
      active_conversation: 32,
    },
    {
      fullName: "Roscoe McArley",
      status: "active",
      gender: "Male",
      addr: "4th Floor",
      email: "rmcarleyw@toplist.cz",
      active_conversation: 33,
    },
    {
      fullName: "Rick Laviss",
      status: "active",
      gender: "Male",
      addr: "Room 776",
      email: "rlavissx@bizjournals.com",
      active_conversation: 34,
    },
    {
      fullName: "Ara Sarchwell",
      status: "active",
      gender: "Agender",
      addr: "Suite 92",
      email: "asarchwelly@multiply.com",
      active_conversation: 35,
    },
    {
      fullName: "Ron Stanman",
      status: "active",
      gender: "Male",
      addr: "Room 1723",
      email: "rstanmanz@cloudflare.com",
      active_conversation: 36,
    },
    {
      fullName: "Beltran Frotton",
      status: "active",
      gender: "Male",
      addr: "PO Box 37112",
      email: "bfrotton10@yandex.ru",
      active_conversation: 37,
    },
    {
      fullName: "Colene Clapshaw",
      status: "active",
      gender: "Female",
      addr: "Room 143",
      email: "cclapshaw11@nationalgeographic.com",
      active_conversation: 38,
    },
    {
      fullName: "Taber Walthall",
      status: "active",
      gender: "Male",
      addr: "Apt 217",
      email: "twalthall12@virginia.edu",
      active_conversation: 39,
    },
    {
      fullName: "Thain Penelli",
      status: "active",
      gender: "Male",
      addr: "Apt 122",
      email: "tpenelli13@google.pl",
      active_conversation: 40,
    },
    {
      fullName: "Elka Rosander",
      status: "active",
      gender: "Female",
      addr: "Apt 1895",
      email: "erosander14@java.com",
      active_conversation: 41,
    },
    {
      fullName: "Danika Davidovitz",
      status: "active",
      gender: "Female",
      addr: "Suite 89",
      email: "ddavidovitz15@addtoany.com",
      active_conversation: 42,
    },
    {
      fullName: "Isidro Wrightson",
      status: "inactive",
      gender: "Male",
      addr: "Suite 40",
      email: "iwrightson16@ucla.edu",
      active_conversation: 43,
    },
    {
      fullName: "Henry Ladley",
      status: "active",
      gender: "Male",
      addr: "Room 237",
      email: "hladley17@tumblr.com",
      active_conversation: 44,
    },
    {
      fullName: "Shannon Haack",
      status: "active",
      gender: "Female",
      addr: "Apt 3",
      email: "shaack18@yellowbook.com",
      active_conversation: 45,
    },
    {
      fullName: "Tanhya Maycock",
      status: "active",
      gender: "Agender",
      addr: "PO Box 85516",
      email: "tmaycock19@cnbc.com",
      active_conversation: 46,
    },
    {
      fullName: "Afton Ogden",
      status: "inactive",
      gender: "Female",
      addr: "16th Floor",
      email: "aogden1a@comcast.net",
      active_conversation: 47,
    },
    {
      fullName: "Travis Kike",
      status: "active",
      gender: "Male",
      addr: "4th Floor",
      email: "tkike1b@omniture.com",
      active_conversation: 48,
    },
    {
      fullName: "Jesselyn Ellaman",
      status: "inactive",
      gender: "Female",
      addr: "Suite 10",
      email: "jellaman1c@hc360.com",
      active_conversation: 49,
    },
    {
      fullName: "Quinn Micah",
      status: "active",
      gender: "Female",
      addr: "Suite 53",
      email: "qmicah1d@reverbnation.com",
      active_conversation: 50,
    },
    {
      fullName: "Arvie Winslow",
      status: "active",
      gender: "Genderfluid",
      addr: "PO Box 7845",
      email: "awinslow1e@answers.com",
      active_conversation: 51,
    },
    {
      fullName: "Allen Friar",
      status: "active",
      gender: "Male",
      addr: "19th Floor",
      email: "afriar1f@goo.gl",
      active_conversation: 52,
    },
    {
      fullName: "Cammie Feitosa",
      status: "active",
      gender: "Female",
      addr: "3rd Floor",
      email: "cfeitosa1g@mozilla.org",
      active_conversation: 53,
    },
    {
      fullName: "Klaus Christou",
      status: "inactive",
      gender: "Male",
      addr: "Apt 1356",
      email: "kchristou1h@ted.com",
      active_conversation: 54,
    },
    {
      fullName: "Isidore Sarch",
      status: "inactive",
      gender: "Male",
      addr: "Room 1911",
      email: "isarch1i@ibm.com",
      active_conversation: 55,
    },
    {
      fullName: "Margie Claiden",
      status: "active",
      gender: "Female",
      addr: "Room 954",
      email: "mclaiden1j@howstuffworks.com",
      active_conversation: 56,
    },
    {
      fullName: "Melvin Roux",
      status: "active",
      gender: "Male",
      addr: "Apt 313",
      email: "mroux1k@aol.com",
      active_conversation: 57,
    },
    {
      fullName: "Morse Giraldon",
      status: "inactive",
      gender: "Male",
      addr: "Apt 1136",
      email: "mgiraldon1l@spiegel.de",
      active_conversation: 58,
    },
    {
      fullName: "Collette Strutt",
      status: "inactive",
      gender: "Female",
      addr: "Suite 62",
      email: "cstrutt1m@people.com.cn",
      active_conversation: 59,
    },
    {
      fullName: "Normy Cain",
      status: "inactive",
      gender: "Male",
      addr: "18th Floor",
      email: "ncain1n@samsung.com",
      active_conversation: 60,
    },
    {
      fullName: "Berte Tolerton",
      status: "inactive",
      gender: "Female",
      addr: "8th Floor",
      email: "btolerton1o@shareasale.com",
      active_conversation: 61,
    },
    {
      fullName: "Peria Jeromson",
      status: "inactive",
      gender: "Bigender",
      addr: "Room 454",
      email: "pjeromson1p@baidu.com",
      active_conversation: 62,
    },
    {
      fullName: "Wilek Monnoyer",
      status: "inactive",
      gender: "Male",
      addr: "Room 156",
      email: "wmonnoyer1q@examiner.com",
      active_conversation: 63,
    },
    {
      fullName: "Andrey Miebes",
      status: "inactive",
      gender: "Male",
      addr: "Suite 38",
      email: "amiebes1r@com.com",
      active_conversation: 64,
    },
    {
      fullName: "Margalit Cardus",
      status: "inactive",
      gender: "Female",
      addr: "Suite 96",
      email: "mcardus1s@nature.com",
      active_conversation: 65,
    },
    {
      fullName: "Uriah Talton",
      status: "inactive",
      gender: "Male",
      addr: "Apt 809",
      email: "utalton1t@freewebs.com",
      active_conversation: 66,
    },
    {
      fullName: "Mada Easey",
      status: "active",
      gender: "Female",
      addr: "18th Floor",
      email: "measey1u@addthis.com",
      active_conversation: 67,
    },
    {
      fullName: "Benjie Lutwyche",
      status: "inactive",
      gender: "Male",
      addr: "Suite 57",
      email: "blutwyche1v@github.com",
      active_conversation: 68,
    },
    {
      fullName: "Haven McClunaghan",
      status: "active",
      gender: "Male",
      addr: "Suite 39",
      email: "hmcclunaghan1w@indiegogo.com",
      active_conversation: 69,
    },
    {
      fullName: "Sherlocke Caren",
      status: "active",
      gender: "Male",
      addr: "PO Box 64277",
      email: "scaren1x@noaa.gov",
      active_conversation: 70,
    },
    {
      fullName: "Ronnie Kenafaque",
      status: "active",
      gender: "Male",
      addr: "PO Box 64716",
      email: "rkenafaque1y@bbb.org",
      active_conversation: 71,
    },
    {
      fullName: "Loraine McBain",
      status: "inactive",
      gender: "Female",
      addr: "PO Box 82205",
      email: "lmcbain1z@netlog.com",
      active_conversation: 72,
    },
    {
      fullName: "Thorstein Cheak",
      status: "active",
      gender: "Male",
      addr: "Suite 8",
      email: "tcheak20@fc2.com",
      active_conversation: 73,
    },
    {
      fullName: "Candida Craker",
      status: "active",
      gender: "Female",
      addr: "20th Floor",
      email: "ccraker21@biblegateway.com",
      active_conversation: 74,
    },
    {
      fullName: "Jolyn Gurnay",
      status: "inactive",
      gender: "Female",
      addr: "Room 199",
      email: "jgurnay22@cbslocal.com",
      active_conversation: 75,
    },
    {
      fullName: "Decca Poser",
      status: "active",
      gender: "Male",
      addr: "Apt 1535",
      email: "dposer23@statcounter.com",
      active_conversation: 76,
    },
    {
      fullName: "Isis Whatling",
      status: "active",
      gender: "Genderqueer",
      addr: "Suite 87",
      email: "iwhatling24@desdev.cn",
      active_conversation: 77,
    },
    {
      fullName: "Karon Simonato",
      status: "active",
      gender: "Female",
      addr: "19th Floor",
      email: "ksimonato25@hibu.com",
      active_conversation: 78,
    },
    {
      fullName: "Shaylynn McPeck",
      status: "active",
      gender: "Female",
      addr: "6th Floor",
      email: "smcpeck26@salon.com",
      active_conversation: 79,
    },
    {
      fullName: "Mason Couve",
      status: "active",
      gender: "Male",
      addr: "Apt 173",
      email: "mcouve27@prlog.org",
      active_conversation: 80,
    },
    {
      fullName: "Mira Walthew",
      status: "active",
      gender: "Female",
      addr: "PO Box 25098",
      email: "mwalthew28@cisco.com",
      active_conversation: 81,
    },
    {
      fullName: "Rosalinda Trunks",
      status: "active",
      gender: "Female",
      addr: "PO Box 4341",
      email: "rtrunks29@addthis.com",
      active_conversation: 82,
    },
    {
      fullName: "Cristin Clarricoates",
      status: "inactive",
      gender: "Female",
      addr: "Suite 24",
      email: "cclarricoates2a@networkadvertising.org",
      active_conversation: 83,
    },
    {
      fullName: "Lawrence Beacroft",
      status: "active",
      gender: "Male",
      addr: "Apt 1351",
      email: "lbeacroft2b@amazonaws.com",
      active_conversation: 84,
    },
    {
      fullName: "Shelden Blakesley",
      status: "active",
      gender: "Male",
      addr: "Room 1008",
      email: "sblakesley2c@reference.com",
      active_conversation: 85,
    },
    {
      fullName: "Zach Ascough",
      status: "inactive",
      gender: "Male",
      addr: "PO Box 2105",
      email: "zascough2d@cafepress.com",
      active_conversation: 86,
    },
    {
      fullName: "Terencio Bellham",
      status: "active",
      gender: "Male",
      addr: "Room 437",
      email: "tbellham2e@furl.net",
      active_conversation: 87,
    },
    {
      fullName: "Nichol Swaden",
      status: "inactive",
      gender: "Female",
      addr: "Room 1977",
      email: "nswaden2f@amazon.co.jp",
      active_conversation: 88,
    },
    {
      fullName: "Arley Mara",
      status: "inactive",
      gender: "Male",
      addr: "Apt 878",
      email: "amara2g@answers.com",
      active_conversation: 89,
    },
    {
      fullName: "Marion Mullender",
      status: "active",
      gender: "Female",
      addr: "Suite 16",
      email: "mmullender2h@usgs.gov",
      active_conversation: 90,
    },
    {
      fullName: "Fianna Shelsher",
      status: "inactive",
      gender: "Female",
      addr: "Suite 69",
      email: "fshelsher2i@discuz.net",
      active_conversation: 91,
    },
    {
      fullName: "Vladamir Sacaze",
      status: "active",
      gender: "Male",
      addr: "Suite 39",
      email: "vsacaze2j@cnbc.com",
      active_conversation: 92,
    },
    {
      fullName: "Elita Brumby",
      status: "active",
      gender: "Female",
      addr: "5th Floor",
      email: "ebrumby2k@ibm.com",
      active_conversation: 93,
    },
    {
      fullName: "Luciano Dykas",
      status: "inactive",
      gender: "Male",
      addr: "Suite 83",
      email: "ldykas2l@topsy.com",
      active_conversation: 94,
    },
    {
      fullName: "Fifi Benfield",
      status: "active",
      gender: "Female",
      addr: "Apt 1845",
      email: "fbenfield2m@china.com.cn",
      active_conversation: 95,
    },
    {
      fullName: "La verne Bartlet",
      status: "inactive",
      gender: "Female",
      addr: "Room 1580",
      email: "lverne2n@princeton.edu",
      active_conversation: 96,
    },
    {
      fullName: "Putnam Huckel",
      status: "active",
      gender: "Male",
      addr: "Room 1982",
      email: "phuckel2o@marriott.com",
      active_conversation: 97,
    },
    {
      fullName: "Hortensia Lasseter",
      status: "active",
      gender: "Female",
      addr: "Room 530",
      email: "hlasseter2p@mapquest.com",
      active_conversation: 98,
    },
    {
      fullName: "Othella Condit",
      status: "inactive",
      gender: "Genderfluid",
      addr: "PO Box 50838",
      email: "ocondit2q@dailymail.co.uk",
      active_conversation: 99,
    },
    {
      fullName: "Annabel Carlon",
      status: "inactive",
      gender: "Female",
      addr: "Apt 917",
      email: "acarlon2r@imageshack.us",
      active_conversation: 100,
    },*/
  ];

  if (name) {
    clients = clients.filter((client) => client.fullName.includes(name));
  }

  if (status) {
    clients = clients.filter((client) => client.status === status);
  }

  return clients;
}
